// <auto-generated />
using System;
using Bica_Ionut_Bogdan.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace Bica_Ionut_Bogdan.Migrations
{
    [DbContext(typeof(Bica_Ionut_BogdanContext))]
    partial class Bica_Ionut_BogdanContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.1.14-servicing-32113")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("Bica_Ionut_Bogdan.Models.CategorieAlergii", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("catAlergii")
                        .IsRequired()
                        .HasMaxLength(30);

                    b.HasKey("ID");

                    b.ToTable("CategorieAlergii");
                });

            modelBuilder.Entity("Bica_Ionut_Bogdan.Models.LocatieDepozite", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("locatieDepozit")
                        .IsRequired()
                        .HasMaxLength(30);

                    b.HasKey("ID");

                    b.ToTable("LocatieDepozite");
                });

            modelBuilder.Entity("Bica_Ionut_Bogdan.Models.Produs", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("CategorieAlergiiID");

                    b.Property<int>("LocatieDepoziteID");

                    b.Property<string>("produsDescriere")
                        .IsRequired()
                        .HasMaxLength(30);

                    b.Property<DateTime>("produsExp");

                    b.Property<string>("produsNume")
                        .IsRequired()
                        .HasMaxLength(30);

                    b.Property<string>("produsSeal")
                        .IsRequired()
                        .HasMaxLength(30);

                    b.HasKey("ID");

                    b.HasIndex("CategorieAlergiiID");

                    b.HasIndex("LocatieDepoziteID");

                    b.ToTable("Produs");
                });

            modelBuilder.Entity("Bica_Ionut_Bogdan.Models.Produs", b =>
                {
                    b.HasOne("Bica_Ionut_Bogdan.Models.CategorieAlergii", "CategorieAlergii")
                        .WithMany()
                        .HasForeignKey("CategorieAlergiiID")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("Bica_Ionut_Bogdan.Models.LocatieDepozite", "LocatieDepozite")
                        .WithMany()
                        .HasForeignKey("LocatieDepoziteID")
                        .OnDelete(DeleteBehavior.Cascade);
                });
#pragma warning restore 612, 618
        }
    }
}
